#!/bin/bash

R="\e[31m"
G="\e[32m"
B="\e[34m"
N="\e[0m"

USERID=$(id -u)

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(basename "$0" .sh)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

PACKAGES=("mysql" "python3" "nginx" "httpd")

mkdir -p "$LOGS_FOLDER"

echo "Script started executing at: $(date)" | tee -a "$LOG_FILE"

if [ "$USERID" -ne 0 ]
then
    echo -e "${R}Please run the script as root user.${N}" | tee -a "$LOG_FILE"
    exit 1
else
    echo -e "${G}You are running as the root user.${N}" | tee -a "$LOG_FILE"
fi

VALIDATE() {
    if [ "$1" -eq 0 ]
    then
        echo -e "${G}Installing $2 ... SUCCESS${N}" | tee -a "$LOG_FILE"
    else
        echo -e "${R}Installing $2 ... FAILED${N}" | tee -a "$LOG_FILE"
        exit 1
    fi
}

for package in "${PACKAGES[@]}"
do
    dnf list installed "$package" &>> "$LOG_FILE"

    if [ $? -ne 0 ]
    then
        echo "$package is not installed. Installing..." | tee -a "$LOG_FILE"
        dnf install -y "$package" &>> "$LOG_FILE"
        VALIDATE $? "$package"
    else
        echo -e "${B}$package is already installed. Nothing to do.${N}" | tee -a "$LOG_FILE"
    fi
done